name: API Test Execution

on:
    push: 
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup java JDK 17'
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'zulu'
                  cache: maven
            - run: mvn --version
            - name: build with maven
              working-directory: "./Automation"
              run: mvn clean
            - name: Testcase execution
              working-directory: "./Automation"
              run: mvn test
              
