name: API Test Execution

on:
    push: 
        branches: ["main"]
jobs:
    SettingupEnv:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup java JDK 17'
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'zulu'
                  cache: maven
            - run: mvn --version
    BuildProject:
        needs: SettingupEnv
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'zulu'
            - name: build with maven
              run: |
                ls
                cd Automation
                mvn clean
    TestExecutionandReports:
        needs: BuildProject
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'zulu'
            - name: Testcase execution
              run: |
                ls
                cd Automation
                mvn test -DsuiteXmlFile=testng.xml -Dmaven.test.failure.ignore=true -fae
            - name: upload Report
              run: |
                ls
                cd Automation
                ls
                cd Extent
                pwd
              if: always()
            - uses: actions/upload-artifact@v2
              with:
                name: test-report
                path: "./Extent"
                


