name: API Test Execution

on:
    push: 
        branches: ["main"]
jobs:
    SettingupEnv:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup java JDK 17'
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'zulu'
                  cache: maven
            - run: mvn --version
            - name: build with maven
              working-directory: ${GITHUB_WORKSPACE}
              run: |
                echo  ${GITHUB_WORKSPACE}
                mvn clean
   
